# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  security_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Clone the repository on the runner
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Restore packages
        run: npm install
      - name: Run Security Tests
        run: npm audit

  build_test:
    runs-on: ubuntu-latest
    needs: security_test

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Clone the repository on the runner
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Restore packages
        run: npm install
      - name: Run Tests and Save Output
        run: npm run test | tee test-results-node-${{matrix.node-version}}.txt
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-node-${{matrix.node-version}}
          path: test-results-node-${{matrix.node-version}}.txt
      - name: Start the project
        run: npm run start &

  deploy:
    runs-on: ubuntu-latest

    needs: build_test
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.STUDENT_REGISTERY_APP_DEPLOY_HOOK }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
